import json
import random
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import RedirectResponse
from sqlalchemy.orm import Session

from app import srs
from app.config import settings
from app.deps import CurrentProfile, DbSession, templates
from app.models import CardState, Deck, Exercise, ExerciseState, ReviewLog, Word
from app.scheduler import build_exercise_session, build_session, exercise_options, pick_distractors

router = APIRouter(prefix="/study")

MODES = {"flashcards", "choice", "typed", "match"}
MODES_BY_KIND = {
    "vocab": {"flashcards", "choice", "typed", "match"},
    "tenses": {"choice", "typed"},
    "gap": {"choice", "typed"},
}
MATCH_PAIRS = 6


@dataclass
class StudySession:
    id: str
    profile_id: int
    deck_id: int
    mode: str
    queue: list[int]
    item_kind: str = "word"  # "word" | "exercise"
    index: int = 0
    results: list[tuple[int, int]] = field(default_factory=list)  # (item_id, grade)


_sessions: dict[str, StudySession] = {}


def _get_session(sid: str, profile_id: int) -> StudySession:
    sess = _sessions.get(sid)
    if sess is None or sess.profile_id != profile_id:
        raise HTTPException(404, "Study session not found (maybe the server restarted)")
    return sess


def _apply_review(db: Session, profile_id: int, item_id: int, grade: int, mode: str, item_kind: str = "word") -> None:
    now = datetime.now(timezone.utc)
    if item_kind == "exercise":
        log_fk = {"exercise_id": item_id}
        card = db.get(ExerciseState, (profile_id, item_id))
        if card is None:
            card = ExerciseState(profile_id=profile_id, exercise_id=item_id, first_seen_at=now)
            db.add(card)
            state = srs.SrsState()
        else:
            state = srs.SrsState(card.ease_factor, card.interval_days, card.repetitions, card.lapses)
    else:
        log_fk = {"word_id": item_id}
        card = db.get(CardState, (profile_id, item_id))
        if card is None:
            card = CardState(profile_id=profile_id, word_id=item_id, first_seen_at=now)
            db.add(card)
            state = srs.SrsState()
        else:
            state = srs.SrsState(card.ease_factor, card.interval_days, card.repetitions, card.lapses)
    new_state, due_at = srs.review(state, grade, now)
    card.ease_factor = new_state.ease_factor
    card.interval_days = new_state.interval_days
    card.repetitions = new_state.repetitions
    card.lapses = new_state.lapses
    card.last_grade = grade
    card.due_at = due_at
    db.add(ReviewLog(profile_id=profile_id, mode=mode, grade=grade, answered_at=now, **log_fk))
    db.commit()


def _parse_misses(raw) -> dict[int, int]:
    """Coerce a client-supplied misses map to {word_id: miss_count}, skipping any
    malformed entry (non-numeric key/value) instead of raising. This payload is
    auto-generated by our own JS in normal use; the leniency is defense against
    malformed clients, where a bad entry is treated as 'no miss recorded'."""
    if not isinstance(raw, dict):
        return {}
    out: dict[int, int] = {}
    for k, v in raw.items():
        try:
            out[int(k)] = int(v)
        except (TypeError, ValueError):
            continue
    return out


def _split_highlight(sentence: str | None, target: str | None):
    """Split `sentence` around the first case-insensitive occurrence of `target`,
    returning (before, match, after) using the sentence's own casing for `match`,
    or None if either is empty or `target` isn't found. Each piece is rendered
    auto-escaped by Jinja and the highlight <span> lives in the template, so there
    is no manual escaping / |safe usage anywhere in this path."""
    if not sentence or not target:
        return None
    idx = sentence.lower().find(target.lower())
    if idx < 0:
        return None
    end = idx + len(target)
    return (sentence[:idx], sentence[idx:end], sentence[end:])


def _parse_options(raw: str | None) -> list[str]:
    """Coerce the client-echoed options payload back to a list of strings,
    returning [] on anything malformed instead of raising (mirrors _parse_misses).
    Purely for re-rendering the feedback grid; never influences grading."""
    if not raw:
        return []
    try:
        data = json.loads(raw)
    except (TypeError, ValueError):
        return []
    if not isinstance(data, list):
        return []
    return [x for x in data if isinstance(x, str)]


def _resolve_current(db: Session, sess: StudySession):
    """Item (Word/Exercise) at sess.index, transparently dropping queue entries
    whose row was deleted mid-session (cascade from another tab). Returns None
    only once the queue is exhausted."""
    model = Exercise if sess.item_kind == "exercise" else Word
    while sess.index < len(sess.queue):
        item = db.get(model, sess.queue[sess.index])
        if item is not None:
            return item
        del sess.queue[sess.index]  # deleted mid-session: drop, next item shifts into place
    return None


def _render_card(request: Request, db: Session, sess: StudySession):
    item = _resolve_current(db, sess)
    if item is None:
        # Failed items get requeued and re-answered, so sess.results can hold
        # multiple entries per word_id. Collapse to the last grade per item
        # (dict() from ordered pairs keeps the final value) for a correct count.
        last_grade = dict(sess.results)
        correct = sum(1 for g in last_grade.values() if g >= 3)
        ctx = {"sess": sess, "correct": correct, "total": len(last_grade), "deck": db.get(Deck, sess.deck_id)}
        _sessions.pop(sess.id, None)
        return templates.TemplateResponse(request, "study/_summary.html", ctx)

    deck = db.get(Deck, sess.deck_id)
    if sess.item_kind == "exercise":
        exercise = item
        ctx = {
            "sess": sess,
            "exercise": exercise,
            "deck": deck,
            "position": sess.index + 1,
            "total": len(sess.queue),
            "highlight": _split_highlight(exercise.prompt, "___") if exercise.type == "gap" else None,
        }
        if sess.mode == "choice":
            options = exercise_options(exercise) + [exercise.answer]
            random.shuffle(options)
            ctx["options"] = options
        return templates.TemplateResponse(request, f"study/_ex_{sess.mode}.html", ctx)

    word = item
    ctx = {
        "sess": sess,
        "word": word,
        "deck": deck,
        "position": sess.index + 1,
        "total": len(sess.queue),
        "highlight": _split_highlight(word.example, word.es) if word.example else None,
    }
    if sess.mode == "choice":
        options = pick_distractors(db, word) + [word.ru]
        random.shuffle(options)
        ctx["options"] = options
    return templates.TemplateResponse(request, f"study/_{sess.mode}.html", ctx)


@router.post("/start")
def start_session(db: DbSession, profile: CurrentProfile, deck_id: int = Form(...), mode: str = Form(...)):
    if mode not in MODES:
        raise HTTPException(400, f"Unknown mode: {mode}")
    deck = db.get(Deck, deck_id)
    if deck is None:
        raise HTTPException(404, "Deck not found")
    allowed = MODES_BY_KIND.get(deck.kind, MODES_BY_KIND["vocab"])
    if mode not in allowed:
        raise HTTPException(400, f"Mode {mode!r} not available for deck kind {deck.kind!r}")

    if deck.kind == "vocab":
        item_kind = "word"
        items = build_session(db, profile, deck_id, settings.session_size)
    else:
        item_kind = "exercise"
        items = build_exercise_session(db, profile, deck_id, settings.session_size)
    if not items:
        return RedirectResponse(f"/blocks/{deck_id}?empty=1", status_code=303)
    if mode == "match":
        items = items[:MATCH_PAIRS]
    sess = StudySession(
        id=uuid.uuid4().hex,
        profile_id=profile.id,
        deck_id=deck_id,
        mode=mode,
        queue=[item.id for item in items],
        item_kind=item_kind,
    )
    _sessions[sess.id] = sess
    return RedirectResponse(f"/study/{sess.id}", status_code=303)


@router.get("/{sid}")
def study_page(sid: str, request: Request, db: DbSession, profile: CurrentProfile):
    sess = _get_session(sid, profile.id)
    deck = db.get(Deck, sess.deck_id)
    if sess.mode == "match":
        # Drop any words deleted mid-session so the queue stays consistent with
        # what /match-results will later grade.
        words = [w for w in (db.get(Word, wid) for wid in sess.queue) if w is not None]
        sess.queue = [w.id for w in words]
        return templates.TemplateResponse(
            request, "study/match.html", {"profile": profile, "sess": sess, "deck": deck, "words": words}
        )
    return templates.TemplateResponse(request, "study/session.html", {"profile": profile, "sess": sess, "deck": deck})


@router.get("/{sid}/card")
def get_card(sid: str, request: Request, db: DbSession, profile: CurrentProfile):
    return _render_card(request, db, _get_session(sid, profile.id))


@router.post("/{sid}/answer")
def answer(
    sid: str,
    request: Request,
    db: DbSession,
    profile: CurrentProfile,
    grade: int | None = Form(None),
    answer: str | None = Form(None),
    options: str | None = Form(None),
):
    sess = _get_session(sid, profile.id)
    if sess.index >= len(sess.queue):
        raise HTTPException(400, "Session already finished")

    item = _resolve_current(db, sess)
    if item is None:
        # Current item (and any remaining) was deleted mid-session: nothing to
        # grade, so just advance to the next card / end-of-session summary.
        return _render_card(request, db, sess)

    if sess.item_kind == "exercise":
        exercise = item
        if sess.mode == "choice":
            final_grade = srs.grade_multiple_choice((answer or "") == exercise.answer)
        elif sess.mode == "typed":
            final_grade = srs.grade_typed(answer or "", exercise.answer)
        else:
            raise HTTPException(400, f"Mode {sess.mode!r} not supported for exercises")

        _apply_review(db, profile.id, exercise.id, final_grade, sess.mode, item_kind="exercise")
        sess.results.append((exercise.id, final_grade))
        sess.index += 1
        if final_grade < 3:
            sess.queue.append(exercise.id)
        return templates.TemplateResponse(
            request,
            "study/_ex_feedback.html",
            {
                "sess": sess,
                "exercise": exercise,
                "given": answer,
                "correct": final_grade >= 3,
                "deck": db.get(Deck, sess.deck_id),
                "options": _parse_options(options),
                "highlight": _split_highlight(exercise.prompt, "___") if exercise.type == "gap" else None,
                "position": sess.index,
                "total": len(sess.queue),
            },
        )

    word = item

    if sess.mode == "flashcards":
        if grade not in (2, 3, 4, 5):
            raise HTTPException(400, "Flashcard grade must be 2-5")
        final_grade = grade
    elif sess.mode == "choice":
        final_grade = srs.grade_multiple_choice((answer or "") == word.ru)
    elif sess.mode == "typed":
        final_grade = srs.grade_typed(answer or "", word.ru)
    else:
        raise HTTPException(400, "Use /match-results for match mode")

    _apply_review(db, profile.id, word.id, final_grade, sess.mode)
    sess.results.append((word.id, final_grade))
    sess.index += 1
    if final_grade < 3:
        sess.queue.append(word.id)

    if sess.mode == "flashcards":
        return _render_card(request, db, sess)
    return templates.TemplateResponse(
        request,
        "study/_feedback.html",
        {
            "sess": sess,
            "word": word,
            "given": answer,
            "correct": final_grade >= 3,
            "deck": db.get(Deck, sess.deck_id),
            "options": _parse_options(options),
            "highlight": _split_highlight(word.example, word.es) if word.example else None,
            "position": sess.index,
            "total": len(sess.queue),
        },
    )


@router.post("/{sid}/match-results")
def match_results(sid: str, request: Request, db: DbSession, profile: CurrentProfile, payload: dict):
    sess = _get_session(sid, profile.id)
    misses = _parse_misses(payload.get("misses"))
    for wid in sess.queue:
        g = srs.grade_match(misses.get(wid, 0) == 0)
        _apply_review(db, profile.id, wid, g, "match")
        sess.results.append((wid, g))
    sess.index = len(sess.queue)
    return _render_card(request, db, sess)
