"""drop profile new_cards_per_day

Revision ID: 0fb88aa6dee8
Revises: fa44adc5d683
Create Date: 2026-07-15 10:36:20.298385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb88aa6dee8'
down_revision: Union[str, None] = 'fa44adc5d683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('new_cards_per_day')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('new_cards_per_day', sa.INTEGER(), nullable=False, server_default='10')
        )

    # ### end Alembic commands ###
