"""learning blocks: exercises, deck kind/level, reviewlog exercise fk

Revision ID: fa44adc5d683
Revises: ec1830514bf9
Create Date: 2026-07-14 16:16:02.222261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa44adc5d683'
down_revision: Union[str, None] = 'ec1830514bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('prompt', sa.String(length=512), nullable=False),
    sa.Column('answer', sa.String(length=128), nullable=False),
    sa.Column('choices', sa.String(length=512), nullable=True),
    sa.Column('hint', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_deck_id'), ['deck_id'], unique=False)

    op.create_table('exercise_states',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_grade', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'exercise_id')
    )
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=16), server_default='vocab', nullable=False))
        batch_op.add_column(sa.Column('level', sa.String(length=8), nullable=True))

    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=True))
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_review_logs_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_review_logs_exercise_id_exercises', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_review_logs_exercise_id_exercises', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_review_logs_exercise_id'))
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('exercise_id')

    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('kind')

    op.drop_table('exercise_states')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_deck_id'))

    op.drop_table('exercises')
    # ### end Alembic commands ###
